[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-std = { version = "1", features = ["attributes", "tokio1"] }
sea-orm-migration = "0.12"
async-trait = "0.1"
