version: '3.8'

services:
  app:
    build: 
      context: .
      target: builder
    container_name: shopist_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/shopist_db
      - RUST_LOG=debug
    volumes:
      - .:/usr/src/app:cached
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/usr/src/app/target
    command: cargo watch -x run
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: shopist_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shopist_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:
  cargo-cache:
  target-cache:

networks:
  app-network:
    driver: bridge
